name: okinawabootcamp
favicon: null
layout_spectrum: 0.50097
typography_spectrum: 0.1177
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#030303'
    - '#613326'
    - '#9dbbd7'
    - '#797365'
  brandStrength: 0.6343699025455862
  lightness: 0.6914972551167011
  saturation: 0.6047862072009593
  rhythmicContrast: 0.411584293236956
purpose: []
