name: okinawabootcamp
favicon: null
layout_spectrum: 1
typography_spectrum: 0.06103
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#874338'
    - '#0a0607'
    - '#dbdfe0'
    - '#888744'
    - '#fc5741'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
