name: okinawabootcamp
favicon: null
layout_spectrum: 1
typography_spectrum: 0.06103
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#dec4a9'
    - '#1e3c72'
    - '#96765f'
    - '#860c0b'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
