name: okinawabootcamp
favicon: null
layout_spectrum: 0.50097
typography_spectrum: 0.1177
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#dec4a9'
    - '#1e3c72'
    - '#96765f'
    - '#860c0b'
  brandStrength: 0.375
  lightness: 0.6914972551167011
  saturation: 0.6047862072009593
  rhythmicContrast: 0.411584293236956
purpose: []
